In [61]:
import pandas as pd

# Load the datasets
df1 = pd.read_csv('1.csv')
df2 = pd.read_csv('2.csv')
df3 = pd.read_csv('3.csv')

df4 = pd.read_csv('4.csv')
df5 = pd.read_csv('5.csv')
df6 = pd.read_csv('6.csv')

df7 = pd.read_csv('7.csv')
df8 = pd.read_csv('8.csv')
df9 = pd.read_csv('9.csv')

df10 = pd.read_csv('10.csv')
df11 = pd.read_csv('11.csv')
df12 = pd.read_csv('12.csv')
# Concatenate the datasets
df= pd.concat([df1, df2, df3,df4,df5,df6,df7,df8,df9,df10,df11,df12])

# Save the merged dataset to a new CSV file
df.to_csv('merged_dataset.csv', index=False)

In [62]:
df.head()

,datetime,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex
0,2023-01-01T00:00:00,0.9,-3.5,72.34,0.0,0.0,2.4,5.2,14.8,0,0
1,2023-01-01T01:00:00,1.4,-3.2,71.22,0.0,0.0,2.4,6.8,10.9,0,0
2,2023-01-01T02:00:00,1.5,-3.0,72.07,0.0,0.0,2.4,6.8,9.0,0,0
3,2023-01-01T03:00:00,1.7,-2.6,73.32,0.0,0.0,2.4,5.6,8.1,0,0
4,2023-01-01T04:00:00,1.5,-2.7,73.60,0.0,0.0,2.4,5.1,7.2,0,0

In [63]:
df.tail()

,datetime,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex
739,2023-12-31T19:00:00,2.6,1.1,89.80,0.0,0.0,1.99,3.6,14.1,0,0
740,2023-12-31T20:00:00,1.8,1.0,94.35,0.0,0.0,1.99,7.4,7.1,0,0
741,2023-12-31T21:00:00,1.6,1.1,96.39,0.0,0.0,0.30,8.8,5.1,0,0
742,2023-12-31T22:00:00,1.3,0.5,94.40,0.0,0.0,1.99,1.8,4.1,0,0
743,2023-12-31T23:00:00,0.8,0.3,96.43,0.0,0.0,1.99,3.6,7.0,0,0

In [64]:
df.shape

(8760, 11)

In [65]:
# Convert the 'datetime' column to datetime format
df['datetime'] = pd.to_datetime(df['datetime'])

# Create 'Date' and 'Hour' columns
df['Date'] = df['datetime'].dt.date
df['Hour'] = df['datetime'].dt.hour

# Drop the original 'datetime' column if no longer needed
df.drop(columns=['datetime'], inplace=True)

# Reorder columns if necessary
df = df[['Date', 'Hour'] + [col for col in df.columns if col not in ['Date', 'Hour']]]

# Display the updated DataFrame
print(df)

           Date  Hour  temp  dew  humidity  precip  snow  snowdepth  \
0    2023-01-01     0   0.9 -3.5     72.34     0.0   0.0       2.40
1    2023-01-01     1   1.4 -3.2     71.22     0.0   0.0       2.40
2    2023-01-01     2   1.5 -3.0     72.07     0.0   0.0       2.40
3    2023-01-01     3   1.7 -2.6     73.32     0.0   0.0       2.40
4    2023-01-01     4   1.5 -2.7     73.60     0.0   0.0       2.40
..          ...   ...   ...  ...       ...     ...   ...        ...
739  2023-12-31    19   2.6  1.1     89.80     0.0   0.0       1.99
740  2023-12-31    20   1.8  1.0     94.35     0.0   0.0       1.99
741  2023-12-31    21   1.6  1.1     96.39     0.0   0.0       0.30
742  2023-12-31    22   1.3  0.5     94.40     0.0   0.0       1.99
743  2023-12-31    23   0.8  0.3     96.43     0.0   0.0       1.99

     windspeed  visibility  solarradiation  uvindex
0          5.2        14.8               0        0
1          6.8        10.9               0        0
2          6.8         9.0               0        0
3          5.6         8.1               0        0
4          5.1         7.2               0        0
..         ...         ...             ...      ...
739        3.6        14.1               0        0
740        7.4         7.1               0        0
741        8.8         5.1               0        0
742        1.8         4.1               0        0
743        3.6         7.0               0        0

[8760 rows x 12 columns]

In [66]:
df.shape

(8760, 12)

In [67]:
df.head()

,Date,Hour,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex
0,2023-01-01,0,0.9,-3.5,72.34,0.0,0.0,2.4,5.2,14.8,0,0
1,2023-01-01,1,1.4,-3.2,71.22,0.0,0.0,2.4,6.8,10.9,0,0
2,2023-01-01,2,1.5,-3.0,72.07,0.0,0.0,2.4,6.8,9.0,0,0
3,2023-01-01,3,1.7,-2.6,73.32,0.0,0.0,2.4,5.6,8.1,0,0
4,2023-01-01,4,1.5,-2.7,73.60,0.0,0.0,2.4,5.1,7.2,0,0

In [68]:
df.tail()

,Date,Hour,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex
739,2023-12-31,19,2.6,1.1,89.80,0.0,0.0,1.99,3.6,14.1,0,0
740,2023-12-31,20,1.8,1.0,94.35,0.0,0.0,1.99,7.4,7.1,0,0
741,2023-12-31,21,1.6,1.1,96.39,0.0,0.0,0.30,8.8,5.1,0,0
742,2023-12-31,22,1.3,0.5,94.40,0.0,0.0,1.99,1.8,4.1,0,0
743,2023-12-31,23,0.8,0.3,96.43,0.0,0.0,1.99,3.6,7.0,0,0

In [69]:
df13 = pd.read_csv('jandec.csv', encoding='cp949')

In [70]:
df13.head()

         Date  Rented Bike Count  Hour
0  2023-01-01               1544     0
1  2023-01-01               1642     1
2  2023-01-01               1118     2
3  2023-01-01                811     3
4  2023-01-01                639     4

In [71]:
df13.shape

(8760, 3)

In [78]:
print('Hour' in df.columns)
print('Hour' in df13.columns)

True
True

In [80]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df13['Date'] = pd.to_datetime(df13['Date'], format='%Y-%m-%d')

# Optional: Ensure 'Hour' columns are of the same type
df['Hour'] = df['Hour'].astype(int)  # Convert to integer if needed
df13['Hour'] = df13['Hour'].astype(int)

# Step 2: Merge the datasets on 'Date' and 'Hour' columns
merged_df = pd.merge(df, df13, on=['Date', 'Hour'], how='inner')  # Use 'inner' for only matching rows, 'outer' for all rows, etc.

# Display the first few rows of the merged dataset
print(merged_df.head())

        Date  Hour  temp  dew  humidity  precip  snow  snowdepth  windspeed  \
0 2023-01-01     0   0.9 -3.5     72.34     0.0   0.0        2.4        5.2
1 2023-01-01     1   1.4 -3.2     71.22     0.0   0.0        2.4        6.8
2 2023-01-01     2   1.5 -3.0     72.07     0.0   0.0        2.4        6.8
3 2023-01-01     3   1.7 -2.6     73.32     0.0   0.0        2.4        5.6
4 2023-01-01     4   1.5 -2.7     73.60     0.0   0.0        2.4        5.1

   visibility  solarradiation  uvindex  Rented Bike Count
0        14.8               0        0               1544
1        10.9               0        0               1642
2         9.0               0        0               1118
3         8.1               0        0                811
4         7.2               0        0                639

In [81]:
merged_df['Weekday'] = merged_df['Date'].dt.dayofweek < 5  # Monday to Friday are 0-4
merged_df['Weekday'] = merged_df['Weekday'].map({True: 'Yes', False: 'No'})

In [82]:
print(merged_df['Date'].head())
print(merged_df['Date'].dtype)

0   2023-01-01
1   2023-01-01
2   2023-01-01
3   2023-01-01
4   2023-01-01
Name: Date, dtype: datetime64[ns]
datetime64[ns]

In [83]:
merged_df.head()

,Date,Hour,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex,Rented Bike Count,Weekday
0,2023-01-01,0,0.9,-3.5,72.34,0.0,0.0,2.4,5.2,14.8,0,0,1544,No
1,2023-01-01,1,1.4,-3.2,71.22,0.0,0.0,2.4,6.8,10.9,0,0,1642,No
2,2023-01-01,2,1.5,-3.0,72.07,0.0,0.0,2.4,6.8,9.0,0,0,1118,No
3,2023-01-01,3,1.7,-2.6,73.32,0.0,0.0,2.4,5.6,8.1,0,0,811,No
4,2023-01-01,4,1.5,-2.7,73.60,0.0,0.0,2.4,5.1,7.2,0,0,639,No

In [84]:
merged_df.shape

(8760, 14)

In [24]:
merged_df.head(50)

,Date,Hour,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex,Rented Bike Count,Weekday
0,2023-01-01,0,0.9,-3.5,72.34,0.0,0.0,2.4,5.2,14.8,0,0,1544,No
1,2023-01-01,1,1.4,-3.2,71.22,0.0,0.0,2.4,6.8,10.9,0,0,1642,No
2,2023-01-01,2,1.5,-3.0,72.07,0.0,0.0,2.4,6.8,9.0,0,0,1118,No
3,2023-01-01,3,1.7,-2.6,73.32,0.0,0.0,2.4,5.6,8.1,0,0,811,No
4,2023-01-01,4,1.5,-2.7,73.60,0.0,0.0,2.4,5.1,7.2,0,0,639,No
5,2023-01-01,5,0.8,-5.6,62.07,0.0,0.0,2.4,9.1,11.6,0,0,540,No
6,2023-01-01,6,-0.2,-5.7,66.24,0.0,0.0,2.4,10.3,9.9,0,0,776,No
7,2023-01-01,7,-1.4,-6.1,70.40,0.0,0.0,2.4,8.5,9.1,0,0,1022,No
8,2023-01-01,8,-1.8,-5.7,74.32,0.0,0.0,2.4,9.4,8.0,1,0,1170,No
9,2023-01-01,9,-1.5,-5.5,74.19,0.0,0.0,3.0,7.0,8.1,72,1,1302,No
10,2023-01-01,10,-0.2,-6.0,64.92,0.0,0.0,2.9,8.3,9.0,234,2,1575,No
11,2023-01-01,11,0.6,-7.0,56.57,0.0,0.0,2.8,12.7,10.0,376,4,1662,No
12,2023-01-01,12,2.0,-6.6,52.87,0.0,0.0,2.5,6.9,10.9,471,5,2021,No
13,2023-01-01,13,3.1,-8.1,43.86,0.0,0.0,2.1,9.2,12.9,506,5,2375,No
14,2023-01-01,14,3.7,-9.3,38.15,0.0,0.0,1.8,10.7,17.7,479,5,2468,No
15,2023-01-01,15,3.1,-10.5,36.11,0.0,0.0,1.6,11.8,18.8,393,4,2757,No
16,2023-01-01,16,2.7,-12.0,33.07,0.0,0.0,1.5,15.8,19.6,248,2,2751,No
17,2023-01-01,17,1.7,-14.4,29.08,0.0,0.0,1.5,11.1,18.8,95,1,2505,No
18,2023-01-01,18,0.2,-13.8,33.97,0.0,0.0,1.5,10.0,18.8,4,0,2038,No
19,2023-01-01,19,-0.6,-12.8,39.37,0.0,0.0,1.4,10.3,19.6,0,0,1681,No
20,2023-01-01,20,-1.6,-12.7,42.52,0.0,0.0,1.4,12.3,18.8,0,0,1501,No
21,2023-01-01,21,-2.0,-12.8,43.51,0.0,0.0,1.4,10.4,18.8,0,0,1403,No
22,2023-01-01,22,-2.6,-13.2,43.87,0.0,0.0,1.4,12.8,18.8,0,0,1189,No
23,2023-01-01,23,-3.3,-13.6,45.00,0.0,0.0,1.4,9.2,18.8,0,0,980,No
24,2023-01-02,0,-4.1,-13.7,47.50,0.0,0.0,1.4,8.2,18.8,0,0,841,Yes
25,2023-01-02,1,-4.8,-14.2,47.99,0.0,0.0,1.3,9.2,18.8,0,0,568,Yes
26,2023-01-02,2,-5.4,-14.4,49.37,0.0,0.0,1.3,8.1,18.8,0,0,304,Yes
27,2023-01-02,3,-6.0,-14.4,51.85,0.0,0.0,1.3,7.4,18.8,0,0,238,Yes
28,2023-01-02,4,-6.3,-15.1,49.95,0.0,0.0,1.3,4.6,18.8,0,0,241,Yes
29,2023-01-02,5,-6.5,-15.0,51.11,0.0,0.0,1.3,6.5,18.8,0,0,696,Yes
30,2023-01-02,6,-6.3,-15.1,49.79,0.0,0.0,1.2,9.4,18.8,0,0,1286,Yes
31,2023-01-02,7,-6.5,-14.9,51.24,0.0,0.0,1.2,10.1,19.6,0,0,3083,Yes
32,2023-01-02,8,-7.2,-15.1,53.13,0.0,0.0,1.2,5.9,19.6,1,0,5843,Yes
33,2023-01-02,9,-6.3,-14.7,51.34,0.0,0.0,2.3,10.0,18.8,75,1,2725,Yes
34,2023-01-02,10,-4.9,-14.7,46.31,0.0,0.0,2.2,9.4,19.6,240,2,1726,Yes
35,2023-01-02,11,-3.8,-14.6,43.09,0.0,0.0,2.2,12.5,18.8,384,4,2034,Yes
36,2023-01-02,12,-2.6,-15.4,36.66,0.0,0.0,2.1,11.5,18.8,482,5,2344,Yes
37,2023-01-02,13,-2.1,-15.7,34.50,0.0,0.0,2.1,12.4,19.6,519,5,2337,Yes
38,2023-01-02,14,-1.3,-15.2,33.91,0.0,0.0,2.0,10.1,19.6,493,5,2401,Yes
39,2023-01-02,15,-0.7,-14.9,33.19,0.0,0.0,1.9,11.0,18.8,406,4,2587,Yes
40,2023-01-02,16,-0.9,-15.0,33.38,0.0,0.0,1.9,10.8,18.8,269,3,3076,Yes
41,2023-01-02,17,-1.7,-14.5,36.79,0.0,0.0,1.8,6.4,19.6,104,1,4545,Yes
42,2023-01-02,18,-2.6,-14.9,38.34,0.0,0.0,1.8,10.0,18.8,4,0,6377,Yes
43,2023-01-02,19,-4.0,-14.7,43.11,0.0,0.0,1.8,9.1,19.6,0,0,3855,Yes
44,2023-01-02,20,-3.5,-15.1,40.25,0.0,0.0,1.8,10.1,18.8,0,0,2963,Yes
45,2023-01-02,21,-3.8,-15.3,40.52,0.0,0.0,1.8,5.8,18.8,0,0,2416,Yes
46,2023-01-02,22,-7.0,-12.4,65.06,0.0,0.0,1.7,8.7,19.6,0,0,1963,Yes
47,2023-01-02,23,-5.6,-14.9,48.21,0.0,0.0,1.7,5.8,18.8,0,0,1312,Yes
48,2023-01-03,0,-6.3,-14.7,51.41,0.0,0.0,1.7,8.6,18.8,0,0,940,Yes
49,2023-01-03,1,-7.2,-14.8,54.39,0.0,0.0,1.7,8.1,19.6,0,0,757,Yes

In [85]:
# Rearrange columns
columns = list(merged_df.columns)
columns.remove('Rented Bike Count')
columns.insert(columns.index('Hour') + 1, 'Rented Bike Count')

# Reorder DataFrame
df_reordered = merged_df[columns]

# Display the DataFrame to verify the change
print(df_reordered.head())

        Date  Hour  Rented Bike Count  temp  dew  humidity  precip  snow  \
0 2023-01-01     0               1544   0.9 -3.5     72.34     0.0   0.0
1 2023-01-01     1               1642   1.4 -3.2     71.22     0.0   0.0
2 2023-01-01     2               1118   1.5 -3.0     72.07     0.0   0.0
3 2023-01-01     3                811   1.7 -2.6     73.32     0.0   0.0
4 2023-01-01     4                639   1.5 -2.7     73.60     0.0   0.0

   snowdepth  windspeed  visibility  solarradiation  uvindex Weekday
0        2.4        5.2        14.8               0        0      No
1        2.4        6.8        10.9               0        0      No
2        2.4        6.8         9.0               0        0      No
3        2.4        5.6         8.1               0        0      No
4        2.4        5.1         7.2               0        0      No

In [86]:
df_reordered.head()

,Date,Hour,Rented Bike Count,temp,dew,humidity,precip,snow,snowdepth,windspeed,visibility,solarradiation,uvindex,Weekday
0,2023-01-01,0,1544,0.9,-3.5,72.34,0.0,0.0,2.4,5.2,14.8,0,0,No
1,2023-01-01,1,1642,1.4,-3.2,71.22,0.0,0.0,2.4,6.8,10.9,0,0,No
2,2023-01-01,2,1118,1.5,-3.0,72.07,0.0,0.0,2.4,6.8,9.0,0,0,No
3,2023-01-01,3,811,1.7,-2.6,73.32,0.0,0.0,2.4,5.6,8.1,0,0,No
4,2023-01-01,4,639,1.5,-2.7,73.60,0.0,0.0,2.4,5.1,7.2,0,0,No

In [87]:
# Save the reordered DataFrame to CSV
df_reordered.to_csv('reordered_dataset.csv', index=False)

# Create a download link using HTML
from IPython.display import HTML

download_link = f'<a href="reordered_dataset.csv" download="reordered_dataset.csv">Click here to download CSV file</a>'
display(HTML(download_link))